packages:
  - packages/*
  - app

catalog:
  '@antfu/eslint-config': ^5.4.1
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@types/node': ^24.9.2
  '@vitest/coverage-v8': ^3.2.4
  cz-git: ^1.12.0
  eslint: ^9.39.0
  eslint-plugin-format: ^1.0.2
  fast-glob: ^3.3.3
  gsap: ^3.13.0
  husky: ^9.1.7
  lint-staged: ^16.2.6
  mediabunny: ^1.24.2
  pixi.js: ^8.14.0
  rolldown: 1.0.0-beta.29
  tsx: ^4.20.6
  type-aide: ^0.0.2
  typescript: ^5.9.3
  unplugin-agent-sync: ^0.1.2
  unplugin-vue-components: ^29.2.0
  vitest: ^3.2.4
  yaml: ^2.8.1
catalogs:
  app:
    '@iconify/json': 2.2.402
    '@vitejs/plugin-vue': ^6.0.1
    '@vue/tsconfig': 0.7.0
    '@vueuse/core': ^13.9.0
    pinia: ^3.0.3
    unocss: ^66.5.4
    unplugin-auto-import: ^20.2.0
    unplugin-vue-router: ^0.16.1
    vite: ^7.1.12
    vite-plugin-vue-devtools: 8.0.3
    vue: ^3.5.22
    vue-router: ^4.5.1
    vue-tsc: ^3.1.2
