packages:
  - packages/*
  - app

catalog:
  '@antfu/eslint-config': ^5.0.0
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@types/node': ^24.1.0
  commitizen: 4.3.1
  cz-git: ^1.12.0
  eslint: ^9.32.0
  eslint-plugin-format: ^1.0.1
  fast-glob: ^3.3.3
  husky: ^9.1.7
  lint-staged: ^16.1.2
  rolldown: 1.0.0-beta.29
  simple-git-hooks: ^2.13.0
  tsx: ^4.20.3
  typescript: ^5.8.3
  unplugin-vue-components: ^28.8.0
  vitest: ^3.2.4
  yaml: ^2.8.0

catalogs:
  app:
    '@vitejs/plugin-vue': ^6.0.0
    '@vue/tsconfig': ^0.7.0
    unplugin-auto-import: ^19.3.0
    unplugin-vue-router: ^0.14.0
    vite: ^7.0.4
    vue: ^3.5.17
    vue-tsc: ^2.2.12
