packages:
  - packages/*
  - app

catalog:
  '@antfu/eslint-config': ^5.0.0
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@types/node': ^24.1.0
  cz-git: ^1.12.0
  eslint: ^9.32.0
  eslint-plugin-format: ^1.0.1
  fast-glob: ^3.3.3
  husky: ^9.1.7
  lint-staged: ^16.1.2
  pixi.js: ^8.12.0
  rolldown: 1.0.0-beta.29
  tsx: ^4.20.3
  type-aide: ^0.0.2
  typescript: ^5.8.3
  unplugin-vue-components: ^29.0.0
  vitest: ^3.2.4
  yaml: ^2.8.0

catalogs:
  app:
    '@iconify/json': 2.2.379
    '@vitejs/plugin-vue': ^6.0.0
    '@vue/tsconfig': ^0.7.0
    pinia: ^3.0.3
    unocss: ^66.4.1
    unplugin-auto-import: ^20.0.0
    unplugin-vue-router: ^0.15.0
    vite: ^7.0.4
    vue: ^3.5.18
    vue-router: ^4.5.1
    vue-tsc: ^3.0.5
    yy-craft: ^1.2.1
