/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./../src/components/appLogo.vue')['default']
    AppLogoLarge: typeof import('./../src/components/appLogoLarge.vue')['default']
    Canvas: typeof import('./../src/components/canvas.vue')['default']
    Nav: typeof import('./../src/components/sider/nav.vue')['default']
    NavItem: typeof import('./../src/components/sider/nav-item.vue')['default']
    PlaybackControls: typeof import('./../src/components/playbackControls.vue')['default']
    ResizableTimeline: typeof import('./../src/components/resizableTimeline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionGroup: typeof import('./../src/components/SelectionGroup.vue')['default']
    Sider: typeof import('./../src/components/sider/sider.vue')['default']
    TimelineWrapper: typeof import('./../src/components/timelineWrapper.vue')['default']
    VideoPreviewCard: typeof import('./../src/components/VideoPreviewCard.vue')['default']
    VideoPreviewList: typeof import('./../src/components/VideoPreviewList.vue')['default']
    VideoPreviewModal: typeof import('./../src/components/VideoPreviewModal.vue')['default']
  }
}
