/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Canvas: typeof import('./../src/components/canvas.vue')['default']
    KeyboardShortcutsHelp: typeof import('../src/components/keyboardShortcutsHelp.vue')['default']
    Nav: typeof import('./../src/components/sider/nav.vue')['default']
    NavItem: typeof import('./../src/components/sider/nav-item.vue')['default']
    PlaybackControls: typeof import('./../src/components/playbackControls.vue')['default']
    ResizableTimeline: typeof import('./../src/components/resizableTimeline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./../src/components/sider/sider.vue')['default']
    TimelineWrapper: typeof import('./../src/components/timelineWrapper.vue')['default']
  }
}
