/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./../src/components/AppLogo.vue')['default']
    AppLogoLarge: typeof import('./../src/components/appLogoLarge.vue')['default']
    Canvas: typeof import('./../src/components/Canvas.vue')['default']
    Nav: typeof import('./../src/components/sider/Nav.vue')['default']
    NavItem: typeof import('./../src/components/sider/NavItem.vue')['default']
    PlaybackControls: typeof import('./../src/components/PlaybackControls.vue')['default']
    ResizableTimeline: typeof import('./../src/components/ResizableTimeline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionGroup: typeof import('./../src/components/SelectionGroup.vue')['default']
    Sider: typeof import('./../src/components/sider/Sider.vue')['default']
    TimelineWrapper: typeof import('./../src/components/TimelineWrapper.vue')['default']
    VideoPreviewCard: typeof import('./../src/components/VideoPreviewCard.vue')['default']
    VideoPreviewList: typeof import('./../src/components/VideoPreviewList.vue')['default']
  }
}
